#!/usr/bin/env python3
# Copyright (c) 2026 4dcitygml
# SPDX-License-Identifier: Apache-2.0
"""One entry point for the operator tools in scripts/ (S14, stage 1).

    python3 -m scripts --list                 # every tool, grouped by purpose
    python3 -m scripts <tool> [arguments]     # the same as python3 scripts/<tool>.py [arguments]
    python3 -m scripts --markdown             # the operator-tools page (docs/operator-tools.md)

Run it from the root of a tools checkout. Every scripts/<tool>.py path keeps working: city CI,
the Exchange Contract (Part C) and the hub bundle call them by path. A tool's line in the
list is the first sentence of its docstring.
"""
from __future__ import annotations

import ast
import runpy
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent

# Maintainer, 2026-09-30: every tool is kept; they are organized by purpose. A new runnable
# module must be placed here (tests/test_operator_tools.py checks it).
GROUPS: "dict[str, tuple[str, ...]]" = {
    "Data preparation": (
        "setup_city_data", "extract_area", "extract_municipality", "split_4th_mesh", "split_utm_tile",
        "merge_to_3rd_mesh", "strip_lod2", "retone_textures", "gc_textures", "make_demo_change",
        "analyze_yearly_citygml_mesh", "plan_yearly_citygml_transition",
    ),
    "Maintenance and quality": (
        "source_update_manifest", "carry_forward_manifest", "identity_manifest", "lifecycle_manifest",
        "lod0_semantic_manifest", "codelist_crosswalk", "carried_codespace_report", "semantic_registry",
        "plateau_codelists", "data_stats", "building_history", "fetch_materials",
    ),
    "Conversion and development": (
        "convert_citygml2_to3_iur4", "generate_uvmap", "diff_citygml", "preview_local",
        "build_bundle", "verify_bundle", "build_common_tools", "release_guard",
    ),
    "CI gates (run by the city workflows)": (
        "pr_classification", "pr_reason", "commit_building_scope", "repo_scope", "validate_citygml",
        "reconstruct_minimal", "reviewability_lint", "texture_check", "citygml_lint", "plausibility_lint",
        "topology_scope", "val3dity_gate", "extract_building_preview", "ci_change_summary",
        "suggest_commit", "pr_comment_metadata", "gate_result", "inspection_summary",
    ),
}


def summary(tool: str) -> str:
    """The first sentence of the tool's docstring (its first paragraph may wrap over several
    lines), read without importing the tool."""
    tree = ast.parse((SCRIPTS / f"{tool}.py").read_text(encoding="utf-8"))
    paragraph = " ".join((ast.get_docstring(tree) or "").strip().split("\n\n")[0].split())
    end = paragraph.find(". ")
    return paragraph[:end + 1] if end >= 0 else paragraph


def listing() -> str:
    lines = []
    for group, tools in GROUPS.items():
        lines.append(group)
        width = max(len(t) for t in tools)
        lines += [f"  {t.ljust(width)}  {summary(t)}" for t in tools]
        lines.append("")
    return "\n".join(lines)


def markdown() -> str:
    lines = [
        "<!-- Copyright (c) 2026 4dcitygml -->",
        "<!-- SPDX-License-Identifier: Apache-2.0 -->",
        "",
        "# Operator tools",
        "",
        "Generated by `python3 -m scripts --markdown` from each tool's docstring; do not edit by hand.",
        "Run a tool from the root of a tools checkout with `python3 -m scripts <tool> [arguments]`",
        "or, as before, `python3 scripts/<tool>.py [arguments]`; `--help` shows its arguments.",
        "",
    ]
    for group, tools in GROUPS.items():
        lines += [f"## {group}", "", "| Tool | What it does |", "|---|---|"]
        lines += [f"| `{t}` | {summary(t).replace('|', '/')} |" for t in tools]
        lines.append("")
    return "\n".join(lines)


def main(argv: "list[str]") -> int:
    if not argv or argv[0] in ("--list", "-l"):
        print(listing(), end="")
        return 0
    if argv[0] == "--markdown":
        print(markdown(), end="")
        return 0
    if argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    tool = argv[0]
    if tool not in {t for tools in GROUPS.values() for t in tools}:
        print(f"Unknown tool: {tool}. `python3 -m scripts --list` shows every tool.", file=sys.stderr)
        return 2
    sys.argv = [str(SCRIPTS / f"{tool}.py"), *argv[1:]]
    runpy.run_module(f"scripts.{tool}", run_name="__main__", alter_sys=True)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
