<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:import namespace="http://www.opengis.net/citygml/2.0" schemaLocation="http://schemas.opengis.net/citygml/2.0/cityGMLBase.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/building/2.0" schemaLocation="http://schemas.opengis.net/citygml/building/2.0/building.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/appearance/2.0" schemaLocation="http://schemas.opengis.net/citygml/appearance/2.0/appearance.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/generics/2.0" schemaLocation="http://schemas.opengis.net/citygml/generics/2.0/generics.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/landuse/2.0" schemaLocation="http://schemas.opengis.net/citygml/landuse/2.0/landUse.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/transportation/2.0" schemaLocation="http://schemas.opengis.net/citygml/transportation/2.0/transportation.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/cityobjectgroup/2.0" schemaLocation="http://schemas.opengis.net/citygml/cityobjectgroup/2.0/cityObjectGroup.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/relief/2.0" schemaLocation="http://schemas.opengis.net/citygml/relief/2.0/relief.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/bridge/2.0" schemaLocation="http://schemas.opengis.net/citygml/bridge/2.0/bridge.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/cityfurniture/2.0" schemaLocation="http://schemas.opengis.net/citygml/cityfurniture/2.0/cityFurniture.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/tunnel/2.0" schemaLocation="http://schemas.opengis.net/citygml/tunnel/2.0/tunnel.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/vegetation/2.0" schemaLocation="http://schemas.opengis.net/citygml/vegetation/2.0/vegetation.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/waterbody/2.0" schemaLocation="http://schemas.opengis.net/citygml/waterbody/2.0/waterBody.xsd"/>
  <xs:import namespace="http://www.opengis.net/citygml/texturedsurface/2.0" schemaLocation="http://schemas.opengis.net/citygml/texturedsurface/2.0/texturedSurface.xsd"/>
  <xs:import namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/uro/2.0" schemaLocation="https://www.geospatial.jp/iur/uro/2.0/urbanObject.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/urf/2.0" schemaLocation="https://www.geospatial.jp/iur/urf/2.0/urbanFunction.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/uro/3.0" schemaLocation="https://www.geospatial.jp/iur/uro/3.0/urbanObject.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/urf/3.0" schemaLocation="https://www.geospatial.jp/iur/urf/3.0/urbanFunction.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/uro/3.1" schemaLocation="https://www.geospatial.jp/iur/uro/3.1/urbanObject.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/urf/3.1" schemaLocation="https://www.geospatial.jp/iur/urf/3.1/urbanFunction.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/uro/3.2" schemaLocation="https://www.geospatial.jp/iur/uro/3.2/urbanObject.xsd"/>
  <xs:import namespace="https://www.geospatial.jp/iur/urf/3.2" schemaLocation="https://www.geospatial.jp/iur/urf/3.2/urbanFunction.xsd"/>
</xs:schema>
