# Copyright (c) 2026 4dcitygml
# SPDX-License-Identifier: Apache-2.0
"""Desktop launchers for a city: a macOS .app bundle or a Windows .lnk shortcut.

The launcher never embeds the clone's path. It embeds only the city id
(owner/repo) and points at the per-user launcher script in the tools folder
(~/Documents/citygml-tools/citygml.sh|.ps1), which resolves the clone from the
shared config at run time. So the icon keeps working wherever it is moved and
even after the clone is moved and re-registered.

Locally created files carry no quarantine attribute (macOS) / mark-of-the-web
(Windows), so the icon opens without a security warning. The bundle is ad-hoc
signed when codesign is available; that is optional.

Standard-library only; macOS uses sips / iconutil / codesign / osascript from the
OS, Windows uses PowerShell (WScript.Shell COM, System.Drawing) — all present by default.
"""
from __future__ import annotations

import plistlib
import re
import shutil
import subprocess
import sys
from pathlib import Path

import runtime


def safe_name(name: str, fallback: str = "CityGML") -> str:
    """A file-name-safe display name (keeps letters of any script, drops path separators etc.)."""
    cleaned = re.sub(r'[\\/:*?"<>|\r\n\t]+', " ", str(name or "")).strip()
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned[:60] or fallback


def ensure_launcher() -> "Path | None":
    """Make sure the per-user launcher exists and, when this program runs as an installed
    version, matches the copy shipped with it (the launcher is the program's, never edited
    by hand; a stale copy would lack newer modes such as --fetch-latest). In a source tree
    an existing launcher is left alone."""
    target, source = runtime.launcher_path(), runtime.launcher_source()
    if not source.is_file():
        return target if target.is_file() else None
    if target.is_file() and (not runtime.running_hub_tag() or target.read_bytes() == source.read_bytes()):
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, target)
    if not runtime.WINDOWS:
        target.chmod(0o755)
    return target


# ---- macOS ----

def _iconset(logo: Path, work: Path) -> "Path | None":
    """PNG logo → .icns via sips + iconutil (both ship with macOS). None when unavailable."""
    if not (logo and logo.is_file()) or not shutil.which("sips") or not shutil.which("iconutil"):
        return None
    iconset = work / "icon.iconset"
    iconset.mkdir(parents=True, exist_ok=True)
    try:
        for size in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                px = size * scale
                name = f"icon_{size}x{size}{'@2x' if scale == 2 else ''}.png"
                subprocess.run(["sips", "-z", str(px), str(px), str(logo), "--out", str(iconset / name)],
                               capture_output=True, check=True, timeout=60)
        icns = work / "icon.icns"
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(icns)],
                       capture_output=True, check=True, timeout=60)
        return icns if icns.is_file() else None
    except (OSError, subprocess.SubprocessError):
        return None


def create_mac_app(dest_dir: Path, display_name: str, city: str,
                   logo: "Path | None" = None, sign: bool = True) -> Path:
    """Create <dest_dir>/<display_name>.app that opens Terminal and runs the per-user launcher."""
    tools_dir, home = runtime.tools_dir(), runtime.home()
    name = safe_name(display_name)
    app = dest_dir / f"{name}.app"
    contents = app / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    if app.exists():
        shutil.rmtree(app)
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)
    # The executable: a shell script that runs the launcher inside Terminal (visible, closable).
    # Only the city id is embedded; the launcher path is derived from $HOME at run time.
    rel = tools_dir.relative_to(home) if str(tools_dir).startswith(str(home)) else None
    launcher = f'"$HOME/{rel.as_posix()}/citygml.sh"' if rel else f'"{tools_dir / "citygml.sh"}"'
    script = (
        "#!/bin/bash\n"
        "# Copyright (c) 2026 4dcitygml — desktop launcher (generated by the hub)\n"
        f"CITY={city!r}\n"
        f"CMD={launcher} \"$CITY\"\n"
        "osascript -e \"tell application \\\"Terminal\\\" to do script \\\"$CMD\\\"\" "
        "-e 'tell application \"Terminal\" to activate' >/dev/null\n"
    )
    exe = macos / "launch"
    exe.write_text(script, encoding="utf-8")
    exe.chmod(0o755)
    info = {
        "CFBundleName": name,
        "CFBundleDisplayName": name,
        "CFBundleIdentifier": "org.4dcitygml.launcher." + re.sub(r"[^A-Za-z0-9]+", "-", city).strip("-").lower(),
        "CFBundleVersion": "1",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "launch",
        "LSMinimumSystemVersion": "12.0",
    }
    icns = _iconset(logo, resources) if logo else None
    if icns:
        info["CFBundleIconFile"] = "icon"
        shutil.rmtree(resources / "icon.iconset", ignore_errors=True)
    with open(contents / "Info.plist", "wb") as fh:
        plistlib.dump(info, fh)
    if sign and shutil.which("codesign"):
        subprocess.run(["codesign", "--force", "-s", "-", str(app)], capture_output=True, timeout=60)
    return app


# ---- Windows ----

def create_windows_shortcut(dest_dir: Path, display_name: str, city: str,
                            logo: "Path | None" = None) -> Path:
    """Create <dest_dir>/<display_name>.lnk that runs the per-user launcher with the city id."""
    name = safe_name(display_name)
    lnk = dest_dir / f"{name}.lnk"
    tools_dir = runtime.tools_dir()
    launcher = runtime.launcher_path()
    icon = ""
    if logo and logo.is_file():
        ico = tools_dir / f"{re.sub(r'[^A-Za-z0-9]+', '-', city)}.ico"
        ps_icon = (
            "Add-Type -AssemblyName System.Drawing; "
            f"$bmp = [System.Drawing.Bitmap]::FromFile('{logo}'); "
            "$sq = New-Object System.Drawing.Bitmap 256,256; $g = [System.Drawing.Graphics]::FromImage($sq); "
            "$g.DrawImage($bmp, 0, 0, 256, 256); $g.Dispose(); "
            "$icon = [System.Drawing.Icon]::FromHandle($sq.GetHicon()); "
            f"$fs = [System.IO.File]::Create('{ico}'); $icon.Save($fs); $fs.Close()"
        )
        try:
            subprocess.run(["powershell", "-NoProfile", "-Command", ps_icon], capture_output=True, timeout=60)
            if ico.is_file():
                icon = str(ico)
        except (OSError, subprocess.SubprocessError):
            icon = ""
    args = f'-NoProfile -ExecutionPolicy Bypass -File "{launcher}" "{city}"'
    ps = (
        "$ws = New-Object -ComObject WScript.Shell; "
        f"$s = $ws.CreateShortcut('{lnk}'); "
        "$s.TargetPath = 'powershell.exe'; "
        f"$s.Arguments = '{args}'; "
        f"$s.WorkingDirectory = '{tools_dir}'; "
        + (f"$s.IconLocation = '{icon}'; " if icon else "")
        + "$s.Save()"
    )
    subprocess.run(["powershell", "-NoProfile", "-Command", ps], capture_output=True, check=True, timeout=60)
    return lnk


def create_shortcut(dest_dir: Path, display_name: str, city: str, logo: "Path | None" = None) -> Path:
    dest_dir.mkdir(parents=True, exist_ok=True)
    if sys.platform == "darwin":
        return create_mac_app(dest_dir, display_name, city, logo)
    if runtime.WINDOWS:
        return create_windows_shortcut(dest_dir, display_name, city, logo)
    raise OSError("Desktop launchers are available on macOS and Windows only")


def reveal(path: Path) -> None:
    """Show the created launcher in Finder / Explorer so it can be dragged to the Desktop or Dock."""
    try:
        if sys.platform == "darwin":
            subprocess.Popen(["open", "-R", str(path)])
        elif sys.platform.startswith("win"):
            subprocess.Popen(["explorer", f"/select,{path}"])
    except OSError:
        pass
